server:
  port: 8080

logging:
  level:
    root: ${ROOT_LOG_LEVEL:WARN}
    org.qubership.integration.platform: DEBUG

spring:
  config:
    import: optional:consul:${CONSUL_URL:http://consul:8500}
  cloud:
    consul:
      config:
        m2m:
          enabled: false
        acl-token: ${CONSUL_ADMIN_TOKEN}

datasource:
  configuration:
    enabled: false

dbaas:
  enabled: false

qip:
  internal-services:
    designtime-catalog: qip-design-time-catalog
    engine: qip-engine

tenant:
  default:
    id: 00000000-0000-0000-0000-000000000000
